# Generated by Django 5.0.2 on 2024-02-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_posttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
