# Generated by Django 5.0.2 on 2024-02-12 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_taxonomygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('lang', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.taxonomygroup')),
                ('main', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='translate_set', to='cms.taxonomy')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child_set', to='cms.taxonomy')),
            ],
        ),
    ]
