# Generated by Django 5.0.2 on 2024-02-13 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_taxonomy_unique_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')], default=0)),
                ('lang', models.CharField(max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('main_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='translate_set', to='cms.post')),
                ('parent_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='child_set', to='cms.post')),
                ('post_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='cms.posttype')),
                ('taxonomy', models.ManyToManyField(blank=True, to='cms.taxonomy')),
            ],
        ),
    ]
